title: chrome.security
email: sereeena@google.com
description: > 
  Chrome Security
baseurl: "/chrome-security-placeholder"
url: https://heisenburger.github.io/chrome-security-placeholder/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
