title: chrome.security
description: > 
  Chrome Security's mission is to make it safe to click on links.
baseurl: "/"
url: https://chrome.security/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
